import assert from 'node:assert/strict';
import {modelFile,scriptFile,scriptModel,extractFiles} from '../lib/spark/artifacts.ts';
const part={name:'A & <B>',shape:'Block',size:[4,1,4],position:[0,1,0],color:[255,0,128]};
const model={name:'../Test model',parts:[part]};
const file=modelFile(JSON.stringify(model));
assert.equal(file.name,'___Test_model.rbxmx');
assert.ok(file.content.includes('A &amp; &lt;B&gt;'));
assert.ok(file.content.includes('<bool name="Anchored">true</bool>'));
const normalizedBlue=modelFile(JSON.stringify({...model,parts:[{...part,color:[0.05,0.35,0.9]}]}));
assert.ok(normalizedBlue.content.includes('<Color3uint8 name="Color3uint8">4279065062</Color3uint8>'));
for(const bad of [{...part,shape:'MeshPart'},{...part,rotation:[0,90,0]},{...part,size:[-1,2,3]},{...part,color:[300,0,0]}]) assert.throws(()=>modelFile(JSON.stringify({...model,parts:[bad]})));
assert.throws(()=>modelFile(JSON.stringify({...model,parts:Array(51).fill(part)})));
const script=scriptFile('-- Spark file: CoinPickup.client.luau\n-- Spark type: LocalScript\n-- Spark location: StarterPlayer.StarterPlayerScripts\nprint("<ok>&")');
assert.equal(script.name,'CoinPickup.client.luau');
assert.ok(scriptModel(script).includes('class="LocalScript"'));
assert.ok(scriptModel(script).includes('<bool name="Disabled">true</bool>'));
assert.ok(scriptModel(script).includes('&lt;ok&gt;&amp;'));
const message='```luau\n'+script.source+'\n```\n```spark-model\n'+JSON.stringify(model)+'\n```';
assert.equal(extractFiles(message).length,2);
assert.equal(extractFiles(message+'\nResponse reached its length limit').length,0);
assert.equal(extractFiles('```spark-model\n{"name":\n```').length,0);
console.log('Artifact validation, escaping, script types, bounded models, and incomplete-output checks passed.');
