import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {studioWeb,studioPlugin,studioPayload} from '../lib/spark/studio.ts';
import {handle} from '../lib/spark/core.ts';
const sql=new DatabaseSync(':memory:');
sql.exec('PRAGMA foreign_keys=ON');
for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+name,'utf8'));
const db={prepare(text){return {args:[],bind(...args){this.args=args;return this},async run(){return sql.prepare(text).run(...this.args)},async first(){return sql.prepare(text).get(...this.args)||null},async all(){return {results:sql.prepare(text).all(...this.args)}}}},async batch(stmts){return Promise.all(stmts.map(s=>s.run()))}};
sql.exec("INSERT INTO users(id,email,password,salt) VALUES ('u','test@example.com','x','x'); INSERT INTO projects(id,user_id,name,description,updated) VALUES ('p','u','Test','',0),('other','u','Other','',0)");
const content='```luau\n-- Spark file: Checkpoint.server.luau\n-- Spark type: Script\n-- Spark location: ServerScriptService\nprint("ok")\n```';
sql.prepare("INSERT INTO messages(id,project_id,role,content,created) VALUES ('m','p','assistant',?,0)").run(content);
const req=(path,method='GET',body,token,place='123')=>new Request('https://spark.test/api/'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token,'X-Spark-Place-Id':place}:{})},body:body?JSON.stringify(body):undefined});
const web=async(action,method='GET',body,project='p')=>(await studioWeb(req('projects/'+project+'/studio',method,body),db,project,action)).json();
const plug=async(path,method='GET',body,token,place)=>(await studioPlugin(req('studio/'+path,method,body,token,place),db,['studio',...path.split('/')])).json();
const first=await web('pair','POST');
assert.equal(first.code.length,72);
assert(!JSON.stringify(sql.prepare('SELECT * FROM studio_connections').get()).includes(first.code));
const pair=await plug('pair','POST',{code:first.code,placeId:'123'});
await assert.rejects(()=>plug('pair','POST',{code:first.code,placeId:'123'}),/expired or already used/);
await assert.rejects(()=>plug('transfers'),/Connect Studio/);
await assert.rejects(()=>plug('transfers','GET',null,pair.token,'456'),/different Studio place/);
await assert.rejects(()=>web('transfers','POST',{messageId:'m'},'other'),/Response not found/);
const job=await web('transfers','POST',{messageId:'m'});
const twice=await web('transfers','POST',{messageId:'m'});
assert.equal(twice.id,job.id);
const list=await plug('transfers','GET',null,pair.token);
assert.equal(list.transfers.length,1);
assert.equal(list.transfers[0].items[0].scriptType,'Script');
assert.equal(list.transfers[0].items[0].location,'ServerScriptService');
await assert.rejects(()=>plug('transfers/'+job.id,'POST',{status:'pending'},pair.token),/Invalid transfer result/);
await plug('transfers/'+job.id,'POST',{status:'applied'},pair.token);
await plug('transfers/'+job.id,'POST',{status:'applied'},pair.token);
await assert.rejects(()=>plug('transfers/'+job.id,'POST',{status:'rejected'},pair.token),/already completed/);
assert.equal((await plug('transfers','GET',null,pair.token)).transfers.length,0);
assert.equal((await web('transfers','POST',{messageId:'m'})).status,'applied');
const otherCode=await web('pair','POST',null,'other');
const otherPair=await plug('pair','POST',{code:otherCode.code,placeId:'123'});
await assert.rejects(()=>plug('transfers/'+job.id,'POST',{status:'applied'},otherPair.token),/unavailable/);
await web(undefined,'DELETE');
await assert.rejects(()=>plug('transfers','GET',null,pair.token),/expired or revoked/);
const expired=await web('pair','POST');
sql.exec('UPDATE studio_connections SET code_expires=0');
await assert.rejects(()=>plug('pair','POST',{code:expired.code,placeId:'123'}),/expired/);
const renewed=await web('pair','POST');
const renewedPair=await plug('pair','POST',{code:renewed.code,placeId:'123'});
sql.exec('UPDATE studio_connections SET token_expires=0');
await assert.rejects(()=>plug('transfers','GET',null,renewedPair.token),/expired/);
assert.throws(()=>studioPayload(content.replace('ServerScriptService','../../Users')),/exact Studio Explorer/);
assert.throws(()=>studioPayload(content+'\n'+content),/same destination/);
assert.throws(()=>studioPayload('incomplete plain response'),/complete response/);
assert.throws(()=>studioPayload('```spark-model\n{"name":"bad","parts":[]}\n```'),/complete response/);
const model=studioPayload('SPARK_MODEL_OPTIONS_V1\n'+JSON.stringify({query:'dog',selectedId:'123',models:[{id:'123',name:'Dog/One'}]}));
assert.equal(model.items[0].assetId,123);
assert.equal(model.items[0].name,'Dog_One');
// Full handler must keep browser mutations behind CSRF and authentication.
assert.equal((await handle(req('projects/p/studio/pair','POST'),{DB:db})).status,403);
assert.equal((await handle(req('projects/p/studio'),{DB:db})).status,401);
assert.equal((await handle(req('studio/transfers'),{DB:db})).status,401);
console.log('PASS Studio pairing, expiry, revocation, project/place isolation, immutable jobs, idempotent receipts, validation, CSRF and authentication');
