"use client";
import {useEffect,useState} from "react";
import AccountMenu from "../account-menu";
import {api} from "../auth-form";
export default function AccountView({user}:{user:any}) {
 const [tab,setTab]=useState("profile"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[color,setColor]=useState(user.avatar_color||"violet");
 useEffect(()=>{const t=new URLSearchParams(location.search).get("tab");if(t&&["profile","settings","billing","security"].includes(t))setTab(t);},[]);
 async function save(e:React.FormEvent<HTMLFormElement>,path:string,extra:any={}){e.preventDefault();setBusy(true);setMessage("");const data=Object.fromEntries(new FormData(e.currentTarget));try{await api(path,path==="profile"?"PATCH":"POST",{...data,...extra});if(path==="security"&&extra.action==="password")location.assign("/login");else setMessage("Saved successfully.");}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <><nav className="nav"><a className="brand" href="/dashboard">✦ <span>Spark</span></a><AccountMenu/></nav><main className="dashboard account-page"><a href="/dashboard">← Back to workspace</a><h1>Your account</h1><div className="account-tabs">{["profile","settings","billing","security"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setMessage("");history.replaceState(null,"","?tab="+t);}}>{t}</button>)}</div><section className="account-panel">
 {(tab==="profile"||tab==="settings")&&<form onSubmit={e=>save(e,"profile",{avatarColor:color})}><h2>{tab==="profile"?"Make it yours":"Appearance"}</h2><span className={"profile-avatar avatar-large "+color}>{user.username?.slice(0,2).toUpperCase()||"✦"}</span><label htmlFor="profile-name">Username</label><input id="profile-name" name="username" defaultValue={user.username||""} required minLength={3} maxLength={24} pattern="[a-zA-Z0-9_]+"/><p className="muted">Your email stays private: {user.email}</p><label>Avatar color</label><div className="avatar-colors">{["violet","blue","rose","green","amber"].map(c=><button type="button" key={c} className={"profile-avatar "+c} aria-label={c} aria-pressed={color===c} onClick={()=>setColor(c)}>{color===c?"✓":"✦"}</button>)}</div><button className="button" disabled={busy}>Save profile</button></form>}
 {tab==="billing"&&<><h2>Plan and credits</h2><h3>{user.billing?.credits?.toLocaleString()||0} Spark Credits available</h3><p>Subscription: {user.billing?.plan||"No plan"} · {user.billing?.status||"none"}</p>{user.billing?.paidUntil&&<p>{user.billing.cancelAtPeriodEnd?"Access ends":"Paid through"}: {new Date(user.billing.paidUntil).toLocaleDateString()}</p>}<p>Monthly plan credits expire at the end of their credit month. Purchased credits do not expire. Larger requests use more credits, based on AI input and output tokens.</p><div className="card-actions"><button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api("billing/portal","POST",{});location.assign(r.url);}catch(e:any){setMessage(e.message);setBusy(false);}}}>Manage subscription and payments</button><a className="button" href="/pricing">Plans and credit packs</a></div></>}
 {tab==="security"&&<><h2>Password and sessions</h2><form onSubmit={e=>save(e,"security",{action:"password"})}><label htmlFor="current">Current password</label><input id="current" name="currentPassword" type="password" autoComplete="current-password" required/><label htmlFor="next">New password</label><input id="next" name="newPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/><p>Changing your password signs out all devices. Sign in again with your new password.</p><button className="button" disabled={busy}>Change password</button></form><hr/><form onSubmit={e=>save(e,"security",{action:"sessions"})}><h3>Sign out other devices</h3><label htmlFor="sessions-password">Confirm current password</label><input id="sessions-password" name="currentPassword" type="password" autoComplete="current-password" required/><button className="button" disabled={busy}>Sign out other devices</button></form></>}
 {message&&<p role="status">{message}</p>}</section></main></>;
}
