export const LEGAL_VERSION = "2026-09-13-draft";
export const legalDocuments = {
  terms: { title: "Terms of Service", sections: [
    ["About Spark", "Spark is an early-stage, independently operated AI workspace for planning Roblox games, generating Luau suggestions, and debugging. It operates from California, United States. Spark is not affiliated with or endorsed by Roblox or OpenAI. These draft terms describe the preview experience; operator identity and a support contact must be added before launch."],
    ["Eligibility and your account", "You must be at least 13 and meet any higher minimum age required where you live. If you are under 18 or the age of legal majority, a parent or legal guardian must review and approve your use and any purchases. Keep your login secure, provide accurate account information, and do not share or sell your account. A signup checkbox is not a substitute for any legally required parental consent."],
    ["Using Spark responsibly", "Use Spark only for lawful purposes and content you have permission to use. Do not upload secrets, passwords, sensitive personal data, or other people's private information. Do not use Spark for malware, account theft, exploitation of other players, harassment, illegal content, infringement, or bypassing service limits. Follow applicable Roblox rules when using or publishing a game."],
    ["AI output and your creations", "AI output may be inaccurate, incomplete, insecure, or similar to output provided to others. Review and test all code in Roblox Studio before using it. Spark does not guarantee a working game, originality, earnings, or compliance with Roblox requirements. You retain your rights in content you submit. To the extent permitted by law and the rights available to Spark, you may use generated output, including commercially. Third-party rights still apply. You give Spark permission to process and store your content only as needed to provide, secure, and support the service."],
    ["Plans, credits, and payments", "Payments are not enabled in this preview. Choosing a plan or pack does not charge you, activate a subscription, or grant credits. Planned prices are in USD. When payments open, the checkout must show the total, any taxes, billing interval, renewal terms, and cancellation method before purchase. Monthly subscriptions would renew monthly and yearly subscriptions annually until cancelled. Yearly plan credits are issued monthly. Unused plan credits expire each monthly cycle; purchased credits carry over without an active subscription. Spark Credits represent service usage, are separate from OpenAI tokens, and have no cash value or transferability except where law requires otherwise. Larger AI requests may consume more credits; usage rates will be disclosed before paid service opens. Any refunds and cancellation rights remain subject to applicable law; final payment terms must be provided before charging."],
    ["Availability and account restrictions", "Features and availability may change during development. Spark may restrict abusive use or suspend access when reasonably necessary to protect users, comply with law, or address violations. Where appropriate, notice and an opportunity to resolve the issue should be provided. Keep your own copies of important work."],
    ["Disclaimers and responsibility", "To the extent permitted by law, the preview is provided as available, without promises that it will be uninterrupted, error-free, or suitable for a particular purpose. You are responsible for reviewing your content and decisions. Nothing in these terms excludes rights or liabilities that cannot legally be excluded, including mandatory consumer protections."],
    ["Changes and applicable law", "Material changes will be communicated before they take effect where required. California law governs to the extent permitted, without taking away mandatory protections where you live. This draft does not impose mandatory arbitration or a class-action waiver. Operator identity and a working contact for questions, notices, and disputes remain to be supplied before launch."],
  ] },
  privacy: { title: "Privacy Policy", sections: [
    ["Scope and draft status", "This policy describes Spark's current preview and planned paid features. Spark operates from California, United States. The operator's legal identity and privacy contact have not yet been finalized. This document must be completed before public launch; it is not a claim that every legal compliance requirement has been met."],
    ["Information processed", "Spark stores your email, a salted password hash rather than a readable password, account identifiers, session records, and the date and document version you accepted. It stores project names, descriptions, prompts, generated replies, and request status. Security controls process request information, including IP-derived rate-limit identifiers. Hosting providers may process IP addresses, browser/device information, and operational logs to deliver and secure the service."],
    ["Why we use information", "Information is used to create and authenticate accounts, save projects and conversations, provide AI assistance, record acceptance, enforce limits, investigate failures and abuse, and meet applicable obligations. When payments are enabled, payment providers will process checkout information and Spark will need subscription and credit records. No payment card details are collected by the current preview."],
    ["AI and service providers", "When AI is enabled, relevant prompts, conversation history, and project details are sent to OpenAI to generate replies. Spark requests that Responses API application state not be stored, but this does not eliminate provider security or abuse-monitoring retention. OpenAI API data is not used for model training by default; provider processing is subject to its policies and account settings. Spark's hosting and database infrastructure, including Sites and Cloudflare, processes data to operate the website. Official Roblox gallery images load from Roblox's CDN, which receives ordinary network request information. Following external links is subject to the destination's policies."],
    ["Cookies and browser storage", "Spark uses an essential session cookie to keep you logged in. Tab-local storage temporarily carries a starting idea from signup into a project, with a 24-hour validity window. This preview does not include advertising trackers or a marketing analytics integration. Third-party hosting and linked sites may have their own practices."],
    ["Sharing and security", "The current application has no feature for selling personal information or sharing it for targeted advertising. Data may be processed by service providers, disclosed when legally required, or used to protect the service. Authorized operators may access records for support, security, and maintenance. Spark uses access checks and password hashing, but no system can promise absolute security. Do not submit content you cannot safely share with the service and its AI provider."],
    ["Retention and deletion", "Project conversations remain in Spark's database until the project is deleted. Project deletion removes its associated messages and requests from the active application database; provider logs or backups may follow separate retention schedules. Account records currently have no automated deletion schedule, and no self-service account deletion or export feature is implemented. A retention schedule and working channel for access, correction, export, and deletion requests must be established before launch. Session cookies expire after seven days. Browser-local drafts are only read within their validity window and can be removed by clearing site storage."],
    ["Your privacy choices", "Depending on your location and applicable law, you may have rights to access, correct, delete, or obtain your information, and other choices regarding its use. California privacy rights apply where the relevant law covers the service; this draft does not assume Spark meets CCPA business thresholds. You may clear cookies and browser storage, though doing so can log you out. Request handling and verification procedures will be provided with the operator's contact details before launch."],
    ["Young users and international processing", "Spark is not intended for children under 13 or below any higher applicable minimum age. Users below the age of legal majority need a parent's or guardian's approval. If child data is identified, the operator must address it under applicable law. Data may be processed in the United States and other countries where service providers operate. Applicable protections and any required transfer arrangements must be assessed before serving additional markets."],
    ["Updates and contact", "Material changes will be communicated as required, with an updated version date. A working privacy/support address and operator identity are pending and must be added before launch. This preview currently cannot receive privacy requests through a dedicated contact channel."],
  ] },
} as const;
